/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
 * Generated on: 24-Aug-2023 17:18:42
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 40
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2023a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 40;
const real32_T B[40] = {
  -0.0002882429108,-0.001982697519,-0.001052211621,-0.0001040179195, -0.00479822699,
  -0.003936131019, 0.001096982276, -0.00907566119, -0.01158319786, 0.004249109887,
   -0.01242559683,  -0.0281526614, 0.009637908079,-0.007540509105, -0.06024632975,
    0.01590904966,   0.0270492807,  -0.1385083944,  0.02024864219,   0.5081212521,
     0.5081212521,  0.02024864219,  -0.1385083944,   0.0270492807,  0.01590904966,
   -0.06024632975,-0.007540509105, 0.009637908079,  -0.0281526614, -0.01242559683,
   0.004249109887, -0.01158319786, -0.00907566119, 0.001096982276,-0.003936131019,
   -0.00479822699,-0.0001040179195,-0.001052211621,-0.001982697519,-0.0002882429108
};
